# Generated by Django 5.2.16 on 2026-09-07 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='primer_apellido',
            field=models.CharField(blank=True, max_length=100, verbose_name='Primer apellido'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='segundo_apellido',
            field=models.CharField(blank=True, max_length=100, verbose_name='Segundo apellido'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='segundo_nombre',
            field=models.CharField(blank=True, max_length=100, verbose_name='Segundo nombre'),
        ),
    ]
