# Generated by Django 5.2.17 on 2026-09-01 22:54

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_solicitado', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('100000'))], verbose_name='Monto solicitado (COP)')),
                ('plazo_meses', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(36)], verbose_name='Plazo en meses')),
                ('tasa_interes_mensual', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Tasa de interés mensual (%)')),
                ('score_calculado', models.IntegerField(blank=True, null=True, verbose_name='Score determinístico')),
                ('nivel_riesgo', models.CharField(blank=True, max_length=20, null=True, verbose_name='Nivel de riesgo')),
                ('estado', models.CharField(choices=[('solicitado', 'Solicitado'), ('evaluado', 'Evaluado'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado'), ('desembolsado', 'Desembolsado'), ('pagado', 'Pagado'), ('mora', 'En Mora')], default='solicitado', max_length=20)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prestamos', to=settings.AUTH_USER_MODEL, verbose_name='Cliente solicitante')),
            ],
            options={
                'verbose_name': 'Préstamo',
                'verbose_name_plural': 'Préstamos',
                'ordering': ['-fecha_solicitud'],
            },
        ),
        migrations.CreateModel(
            name='Cuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_cuota', models.IntegerField(verbose_name='Número de cuota')),
                ('fecha_vencimiento', models.DateField(verbose_name='Fecha de vencimiento')),
                ('valor_cuota', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor cuota')),
                ('interes', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Interés período')),
                ('abono_capital', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Abono capital')),
                ('saldo_pendiente', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Saldo pendiente')),
                ('pagada', models.BooleanField(default=False, verbose_name='¿Pagada?')),
                ('prestamo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuotas', to='loans.prestamo', verbose_name='Préstamo')),
            ],
            options={
                'verbose_name': 'Cuota',
                'verbose_name_plural': 'Cuotas',
                'ordering': ['numero_cuota'],
                'unique_together': {('prestamo', 'numero_cuota')},
            },
        ),
    ]
