# Generated by Django 5.2.16 on 2026-09-07 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfilcliente',
            old_name='ciudad',
            new_name='ciudad_nacimiento',
        ),
        migrations.AddField(
            model_name='perfilcliente',
            name='ciudad_residencia',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='perfilcliente',
            name='contacto_respaldo_nombre',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='perfilcliente',
            name='contacto_respaldo_parentesco',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='perfilcliente',
            name='contacto_respaldo_telefono',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='perfilcliente',
            name='nacionalidad',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='perfilcliente',
            name='pais_residencia',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
