# Generated by Django 5.2.17 on 2026-09-17 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0003_solicitudcredito'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilcliente',
            name='gastos_mensuales',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='perfilcliente',
            name='ingresos_mensuales',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
            preserve_default=False,
        ),
    ]
