# Generated by Django 5.2.17 on 2026-09-17 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0004_perfilcliente_gastos_mensuales_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudcredito',
            name='extracto_bancario_1',
            field=models.FileField(blank=True, null=True, upload_to='solicitudes/extractos/'),
        ),
        migrations.AddField(
            model_name='solicitudcredito',
            name='extracto_bancario_2',
            field=models.FileField(blank=True, null=True, upload_to='solicitudes/extractos/'),
        ),
        migrations.AddField(
            model_name='solicitudcredito',
            name='extracto_bancario_3',
            field=models.FileField(blank=True, null=True, upload_to='solicitudes/extractos/'),
        ),
    ]
