# Generated by Django 5.2.17 on 2026-09-21 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0005_solicitudcredito_extracto_bancario_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudcredito',
            name='plazo_meses',
            field=models.IntegerField(default=12),
        ),
    ]
